# *******************************************
# SConstruct - Define the SCons build process
# *******************************************
# All code is in :doc:`SConstruct.py`. Execute that.
SConscript('SConstruct.py')
